TranslationError: You seems to forgot parentheses after method call, part 2
git-svn-id: http://pony.tigris.org/svn/pony/trunk@2041 698dff77-f410-0410-8918-cf622e150f36