Fix test_operations.
Before:
pony$ python2 pony/orm/examples/test_operations.py
Traceback (most recent call last):
  File "pony/orm/examples/test_operations.py", line 2, in <module>
    from pony.orm.migrating.diagram_ops import *
ImportError: No module named migrating.diagram_ops

pony$ python3 pony/orm/examples/test_operations.py
  File "pony/orm/examples/test_operations.py", line 36
    print db.schema.generate_create_script()
           ^
SyntaxError: invalid syntax

After:
pony$ python2 pony/orm/examples/test_operations.py
class Person(Entity):
    id = PrimaryKey(int, auto=True)
    name = Required(str)
    age = Required(int)
()
CREATE TABLE "person" (
  "id" INTEGER CONSTRAINT "pk_person" PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "age" INTEGER UNIQUE NOT NULL
)
CREATE TABLE "contact" (
  "id" INTEGER CONSTRAINT "pk_contact" PRIMARY KEY AUTOINCREMENT,
  "type" TEXT NOT NULL,
  "value" TEXT NOT NULL
);

CREATE TABLE "person" (
  "id" INTEGER CONSTRAINT "pk_person" PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL
)
{(u'person',): <pony.orm.dbproviders.sqlite.SQLiteForeignKey object at 0x7f6eb387e390>}

pony$ python3 pony/orm/examples/test_operations.py
(same as python 2)